
all:
	g++ -std=c++17 -DSCDEKKERS  main.cpp -lpthread -Wall -Wextra -Wpedantic -Wshadow -g -fsanitize=thread -O3 -o scdekker
	g++ -std=c++17 -DRDEKKERS   main.cpp -lpthread -Wall -Wextra -Wpedantic -Wshadow -g -fsanitize=thread -O3 -o rdekkers
	g++ -std=c++17 -DTSODEKKERS main.cpp -lpthread -Wall -Wextra -Wpedantic -Wshadow -g -fsanitize=thread -O3 -o tsodekkers
