all:
	# g++ -std=c++17 main.cpp -lpthread -Wall -Wextra -Wshadow -g -fsanitize=thread -o final
	# g++ -std=c++17 Q4.cpp -lpthread -Wall -Wextra -Wshadow -g -fsanitize=thread -o q4
	g++ -std=c++17 Q5_partA.cpp -lpthread -Wall -Wextra -Wshadow -g -fsanitize=thread -o q5_a
clean:
	rm final q4 q5_a