
all:
	g++ -std=c++17 main1.cpp -lpthread -Wall -Wextra -Wshadow -g -fsanitize=thread -o relaxed_sb
	g++ -std=c++17 main2.cpp -lpthread -Wall -Wextra -Wshadow -g -fsanitize=thread -o sync_sb
	g++ -std=c++17 main3.cpp -lpthread -Wall -Wextra -Wshadow -g -fsanitize=thread -o sc_sb
